### ISSUE TITLE
i can't run this project. vicalloy!

### ISSUE THREAD

**Issue by huliangkira** [vicalloy/django-lb-workflow#1]
Request Method: | GET
-- | --
http://127.0.0.1:8000/wf/list/
1.11.13
TypeError
'AnonymousUser' object is not iterable
C:\Python34\lib\site-packages\django\utils\functional.py in inner, line 239
C:\Python34\python.exe
3.4.4
['C:\\Users\\Administrator\\Downloads\\django-lb-workflow-master\\django-lb-workflow-master',  'C:\\Users\\Administrator\\Downloads\\django-lb-workflow-master\\django-lb-workflow-master\\testproject',  'C:\\Python34\\lib\\site-packages\\django_lb_adminlte-0.9.6-py3.4.egg',  'C:\\Python34\\lib\\site-packages\\django_compressor-2.2-py3.4.egg',  'C:\\Python34\\lib\\site-packages\\django_lb_workflow-0.9.0-py3.4.egg',  'C:\\Windows\\SYSTEM32\\python34.zip',  'C:\\Python34\\DLLs',  'C:\\Python34\\lib',  'C:\\Python34',  'C:\\Python34\\lib\\site-packages']
Thu, 31 May 2018 07:44:12 +0000

**Comment by vicalloy** [comment]
You should login, `/wf/list/` is only available for authorized user.
url for login is `http://127.0.0.1:8000/admin/login/`
