### ISSUE TITLE
设计问题

### ISSUE THREAD

**Issue by suntekma** [vicalloy/django-lb-workflow#10]
我们需要做个自动化权限申请：
用户提交信息->用户主管审批->调用 python过程 或者 http请求 给用户添加管理员权限。->到期自动回收

调用 python过程 或者 http请求 给用户添加管理员权限 ：

    这个过程我们能否修改node model ，加一个执行命令框。审批完之后 自动执行。

到期自动回收：

    做个计划任务定时执行？回收权限？

**Comment by vicalloy** [comment]
1. 在子类里重写`BaseWFObj .on_complete()`这个函数，这个函数会在流程结束的时候调用。
2. 把权限回收的时间写在model里，用定时任务每分钟检查一次，将到期权限回收。

**Comment by suntekma** [comment]
BaseWFObj .on_complete()这个函数 继承自哪里来得到这个函数？

**Comment by suntekma** [comment]
解决了，thx 。
