### ISSUE TITLE
 edit 之后需要返回 Draft 同意，然后到当前审批者

### ISSUE THREAD

**Issue by suntekma** [vicalloy/django-lb-workflow#12]
请指导一下，这个如何实现

**Comment by vicalloy** [comment]
新建一个流程分支，“申请人修改”，处理人为申请人，允许编辑。在”申请人修改”结束后再返回当前节点。

**Comment by suntekma** [comment]
有微信吗？我们加一下好交流

**Comment by suntekma** [comment]
并不是申请人自己修改，是当前审批者修改之后，返回到申请人，申请人同意再返回当前审批者。

**Comment by vicalloy** [comment]
在表单里加一个隐藏字段标记是否编辑过。在提交后根据这个标记判断走哪个分支。在流程流转后记得清理标记，不然之后每次都会走编辑的分支。

**Comment by vicalloy** [comment]
可以把微信号发到我的邮箱，不太适合放这里。

**Comment by suntekma** [comment]
每一步流程 都会有 Edit，如果有编辑都会需要申请者确认。我是想我是不是 把Edit 做成 类似BatchExecuteRejectTransitionView 和  ExecuteRejectTransitionView 类

**Comment by vicalloy** [comment]
是的，理论上要做成ExecuteRejectTransitionView这样的类。
不过实际要处理的东西还有点多。
如果没有特殊需求建议直接在编辑的时候做个操作，在编辑完成后将当前处理人修改为申请人。

注：
- 不是很确定现在是否会留下编辑记录，如果没有编辑日志，得留下一条编辑日志。
- 如果存在多个审批人，直接修改审批人的方式会有点问题。
