### ISSUE TITLE
求指导

### ISSUE THREAD

**Issue by suntekma** [vicalloy/django-lb-workflow#4]
需要同步LDAP用户，在审批流进行时能读取LDAP用户属性进行spilt.比如potter用户经理是tom.用户提交后直接给经理审批。审批直接设置为USER.manager.层级关系都包含在LDAP中。请给我一个思路。我们自己修改代码。

**Comment by vicalloy** [comment]
Django允许使用用户自定义的User类替代auth里默认的User。
建议你们定义自己的User类，然后添加自定义属性或函数来获取审批人。如：
`user.manager()`
设置审批人时`[o. created_by.manager()]`

审批人设置你可以参考代码：
https://github.com/vicalloy/django-lb-workflow/blob/master/lbworkflow/core/userparser.py
https://github.com/vicalloy/django-lb-workflow/blob/master/lbworkflow/tests/test_userparser.py

如果你们审批人规则设置非常复杂，默认的`SimpleUserParser `无法满足要求你可以实现自己的`UserParser `。

**Comment by suntekma** [comment]
你们定义自己的User类，可以实现，但是LDAP用户 要登录才能 同步到User表。如果用户主管没有登录过系统，用户提交申请将无法获取审批人。这个有什么好方法处理吗？
