### ISSUE TITLE
pip install error...

### ISSUE THREAD

**Issue by miumiusun** [vicalloy/django-lb-workflow#6]
hi, my pc is win7/64byte.
My first try, pip install --upgrade django-lb-workflow, the console tell me :  "error: command 'cl.exe' failed: No such file or directory", then I made Path variables.

Then, my second try, the console tell the bellow:
    ----------------------------------------
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -INone -IC:\Users\Administrator\AppData\Local\Programs\Python\Python36\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python36\include /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win-amd64-3.6\Release\pygraphviz/graphviz_wrap.obj
    graphviz_wrap.c
    c:\users\administrator\appdata\local\programs\python\python36\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: "io.h": No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\Hostx64\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------

what can I do? Thank U very much .

**Comment by vicalloy** [comment]
`pygraphviz` install failed.
You can read the follow article to install `pygraphviz` on windows.
https://stackoverflow.com/questions/40809758/howto-install-pygraphviz-on-windows-10-64bit

**Comment by miumiusun** [comment]
3Q~!
I follow the up blog, and go to the step4, 
my console come with: 
"pygraphviz-1.3.1-cp34-none-win_amd64.whl is not a supported wheel on this platfo
rm."
My python version is 3.6.4, dose that matter?
Thank U very much.

**Comment by vicalloy** [comment]
`pygraphviz-1.3.1-cp34-none-win_amd64.whl` is only for `python3.4`.
`pygraphviz` is used to generate flow chart, you can use `lb-workflow` without `pygraphviz`. 

BTW:
Windows is not a good choose for python developer.

**Comment by vicalloy** [comment]
remove pygraphviz dependence.
