### ISSUE TITLE
点击 Flowchart 报错

### ISSUE THREAD

**Issue by suntekma** [vicalloy/django-lb-workflow#8]
Request Method: | GET
-- | --
http://127.0.0.1:8000/wf/flowchart/process/issue/
2.0.6
NameError
name 'pgv' is not defined
F:\NeweggFlow\src\lbworkflow\views\flowchart.py in generate_process_flowchart, line 45
C:\Program Files (x86)\Python36-32\python.exe
3.6.0
['F:\\NeweggFlow\\src',  'F:\\NeweggFlow\\src',  'C:\\Program Files (x86)\\Python36-32\\DLLs',  'C:\\Program Files (x86)\\Python36-32\\lib',  'C:\\Program Files (x86)\\Python36-32',  'C:\\Program Files (x86)\\Python36-32\\lib\\site-packages',  'C:\\Program Files '  '(x86)\\Python36-32\\lib\\site-packages\\pip-10.0.1-py3.6.egg',  'C:\\Program Files (x86)\\Python36-32\\lib\\site-packages\\win32',  'C:\\Program Files (x86)\\Python36-32\\lib\\site-packages\\win32\\lib',  'C:\\Program Files (x86)\\Python36-32\\lib\\site-packages\\Pythonwin',  'C:\\Program Files (x86)\\Python36-32\\python36.zip']
Thu, 7 Jun 2018 07:58:30 +0000

**Comment by vicalloy** [comment]
需要安装`pygraphviz`这个库，没有安装`pygraphviz`无法生成流程图。
`pygraphviz`里面包含了c代码，需要编译，在windows下安装比较麻烦，你可以试着安装一下。
#6 也是说的这个问题。
