### ISSUE TITLE
LDAP 验证User 出现问题，求教下

### ISSUE THREAD

**Issue by suntekma** [vicalloy/django-lb-workflow#9]
你们定义自己的User类，可以实现，但是LDAP用户 要登录才能 同步到User表。如果用户主管没有登录过系统，用户提交申请将无法获取审批人。这个有什么好方法处理吗？

**Comment by vicalloy** [comment]
写一个用户同步脚本，把LDAP里的用户同步到Django。
写一个定时任务，定时同步。

**Comment by suntekma** [comment]
django-python3-ldap    有一个自带的 ldap_sync_users 命令 可以实现这个操作。谢谢指导。
